### PR TITLE
Update strings.py

### PR DESCRIPTION
**Pull request by n3storm**

### CODE REVIEW

**Comment by n3storm** [comment]
Your fork is the only one working with django 1.8.3 except for the import at strings.py ugettext. Changing to ugettext_lazy works.

**Comment by rpalacios** [comment]
We finally left this library because it throws many exceptions when running migrating or synchronizing db.  This is because it assumes that db tables exists on `SequenceField.__init__`.

We have created a new one based on Odoo sequences style and enhanced with very customizable behaviour.

**Comment by rpalacios** [comment]
I will ask my boss about put that code on github. It is not very large.

**Comment by n3storm** [comment]
hi @rpalacios, that code on github will be great! We like odoo style too.

**Pull request merged**
